/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/lamplight.glb -S -T 
Files: ./public/lamplight.glb [4.55MB] > /mnt/c/Users/adnaan/Desktop/portfolio-adnaan/lamplight-transformed.glb [228.57KB] (95%)
*/
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';
export default function Model(props) {
  const { nodes, materials } = useGLTF('/lamplight-transformed.glb')
  const lampRef = useRef();
  const lightRef = useRef();

  useFrame(() => {
    if (lightRef.current && lampRef.current) {
      lightRef.current.target = lampRef.current;
    }
  })

  return (
    <group {...props} dispose={null}>

      <mesh ref={lampRef} geometry={nodes.Bulb.geometry} material={materials.re_lamp_02} position={[0, 0.09, -0.24]}>
        <ambientLight intensity={0.3} />
        <spotLight
          position={[0,2,0]}
          castShadow
          target={lampRef.current}
          color={"#E7A60BFF"}
          ref={lightRef} angle={0.5} penumbra={0.6} decay={0} intensity={3} volumetric />
        </mesh>
    </group>
  )
}


