/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/snakeplant.glb -S -T 
Files: ./public/snakeplant.glb [1.8MB] > /mnt/c/Users/adnaan/Desktop/portfolio-adnaan/snakeplant-transformed.glb [295.52KB] (84%)
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-snake-plant-237210b3b20a492c851c0145fe316ea7
Title: Low-poly snake plant
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/snakeplant.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[0.008, 0.056, -0.022]} scale={0.067} />
      <mesh geometry={nodes.Cylinder_Flowerpot_0.geometry} material={materials.Flowerpot} position={[0, -0.234, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.24} />
      <mesh geometry={nodes.Cylinder001_Soil_0.geometry} material={materials.Soil} position={[0, -0.234, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.24} />
    </group>
  )
}

useGLTF.preload('/snakeplant.glb')
