/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/snakeplant.glb —transform —simplify 
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-snake-plant-237210b3b20a492c851c0145fe316ea7
Title: Low-poly snake plant
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/snakeplant.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Plane_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[0.808, 5.561, -2.192]} scale={6.66} />
        <mesh geometry={nodes.Cylinder_Flowerpot_0.geometry} material={materials.Flowerpot} position={[0, -23.353, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={24.004} />
        <mesh geometry={nodes.Plane001_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[8.122, 3.895, -5.482]} rotation={[0, -1.049, 0]} scale={6.382} />
        <mesh geometry={nodes.Plane002_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[-0.258, 7.913, 3.609]} rotation={[3.012, -1.057, 3.062]} scale={6.382} />
        <mesh geometry={nodes.Plane003_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[3.916, 2.29, 3.548]} rotation={[3.043, -0.759, -3.077]} scale={6.382} />
        <mesh geometry={nodes.Plane004_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[-0.562, 5.561, -1.613]} rotation={[Math.PI, -0.8, Math.PI]} scale={6.66} />
        <mesh geometry={nodes.Plane005_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[-3.296, 3.895, 5.927]} rotation={[Math.PI, 0.249, -Math.PI]} scale={6.382} />
        <mesh geometry={nodes.Plane006_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[-3.983, 7.913, -6.418]} rotation={[2.922, 1.274, -2.897]} scale={6.382} />
        <mesh geometry={nodes.Plane007_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[-9.732, 2.29, -2.126]} rotation={[1.442, 1.498, -1.309]} scale={6.382} />
        <mesh geometry={nodes.Plane008_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[-0.484, 5.561, -2.839]} rotation={[Math.PI, 1.43, -Math.PI]} scale={6.66} />
        <mesh geometry={nodes.Plane009_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[-7.5, 3.895, -6.724]} rotation={[0, 1.164, 0]} scale={6.382} />
        <mesh geometry={nodes.Plane010_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[4.799, 7.913, -5.462]} rotation={[0.064, 0.132, 0.025]} scale={6.382} />
        <mesh geometry={nodes.Plane011_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[2.249, 2.29, -8.767]} rotation={[0.073, -0.167, 0.145]} scale={6.382} />
        <mesh geometry={nodes.Plane012_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[11.806, 2.29, -9.944]} rotation={[0.143, -1.043, 0.256]} scale={6.382} />
        <mesh geometry={nodes.Plane013_SnakePlant_leaf_0.geometry} material={materials.SnakePlant_leaf} position={[-11.354, 2.29, 6.09]} rotation={[3.023, 0.921, -2.914]} scale={6.382} />
        <mesh geometry={nodes.Cylinder001_Soil_0.geometry} material={materials.Soil} position={[0, -23.353, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={24.004} />
      </group>
    </group>
  )
}


